FROM golang:1.26 AS build
WORKDIR /src
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/sandbox-broker ./cmd/sandbox-broker

FROM gcr.io/distroless/static-debian11
COPY --from=build /out/sandbox-broker /usr/local/bin/sandbox-broker
USER 65532:65532
ENTRYPOINT ["/usr/local/bin/sandbox-broker"]
